# Generated by Django 4.1 on 2022-08-07 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workout",
            name="description",
            field=models.TextField(),
        ),
    ]
